### ISSUE TITLE
Deploy protocol server to samagra server

### ISSUE THREAD

**Issue by karntrehan** [Konnect-Agri/AgriDex-Beckn#10]
Once #9 is done we shall deploy the protocol server to samagra servers. 

Server to be used: 64.227.181.5 => konnect.samagra.io

To be deployed on a different port.

**Comment by karntrehan** [comment]
@techsavvyash to share repos here to deploy.

**Comment by techsavvyash** [comment]
https://github.com/ChakshuGautam/beckn-protocol-server-network
https://github.com/ChakshuGautam/beckn-protocol-server-client

The below video can be used to setup the protocol server
https://drive.google.com/file/d/13hVyBNkzD0pSjaS9N1-NaeSqmJwA6Jtq/view

These are the repos for the protocol server deployment

@karntrehan please have a look

**Comment by karntrehan** [comment]
Protocol server did not work locally. BPP responses were not flowing through. Issue to be raised on Beckn Discord to take this forward. Could be a beckn registry issue. 

Local registry created by Abhishek to also be tested.

**Comment by karntrehan** [comment]
Protocol server working locally. Some gotchas identified. 

Step by step guide to be created by @techsavvyash and shared. 

Registry used in beckn. Would need to load test. Self hosted registry is not clear currently.

**Comment by techsavvyash** [comment]
- Created a working postman collection to be shared with the bank and other concerned parties, which can be found [here](https://api.postman.com/collections/18245860-96549686-ffc1-498a-8f62-3bf78dcef743?access_key=PMAT-01GXWGF8AWRMRGS9YJ0R9V4T3E).

- The local versions of protocol server still does not support the `track` and `update` methods and raised those with the Beckn team on their officail discord server. The message can be found [here](https://discord.com/channels/933320455903907840/976854793031139378/1105506094643695732). Also contacted the maintainer/POC for protocol server regarding the same, waiting to hear back.

- Because of the above point, currently we are using Beckn's already deployed protocol server instance in the postman for the banks to play around with.

**Comment by karntrehan** [comment]
Postman collection https://elements.getpostman.com/redirect?entityId=18245860-96549686-ffc1-498a-8f62-3bf78dcef743&entityType=collection
